---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-release
  namespace: default
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo-app
        namespace: flux-system
  interval: 1m0s
  valuesFrom:
  - kind: ConfigMap
    name: podinfo-values

